### ISSUE TITLE
Nombres más descriptivos

### ISSUE THREAD

**Issue by gbosetti** [Banegasn/web-extension-training#4]
Por ejemplo, la clase Web debería ser algo más específica, ya que no representa toda la Web. La repsonsabilidad de esa clase es analizar en documento actual que el usuario está visitando y extraer los datos que luego van a servir para que otra clase haga algo con ellos. Entonces, el nombre debería tener que ver con eso.

**Comment by Banegasn** [comment]
Si lo que pasa es que esa misma clase obtiene los titulos de la web del resultado de busqueda de wikipedia. **DocumentTitleFinder** se me ocurre de ultima, pero no se
